# -*- coding: utf-8 -*-
"""LVADSUSR180_lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3JKYdZQtmIBnV_6kdj97qjjiY9gFpuF
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score,accuracy_score,precision_score,confusion_matrix,ConfusionMatrixDisplay

df=pd.read_csv(r'https://raw.githubusercontent.com/Deepsphere-AI/LVA-Batch5-Assessment/main/booking.csv')

df.head()

df.isnull().sum()

df.duplicated().sum()

df.shape

df.dropna(inplace=True)

df.columns.tolist()

df.drop(['Booking_ID','date of reservation'],axis=1,inplace=True)

cat_cols=df.select_dtypes(exclude='number').columns.tolist()

cat_cols

for i in cat_cols:
 print(df[i].value_counts())



for i in cat_cols:
 sns.countplot(data=df,x=i)
 plt.show()

for i in cat_cols:
  print(df[i].unique())
  print("---")

num_cols=df.select_dtypes(include='number').columns.tolist()

for i in df.columns.tolist():
  sns.boxplot(data=df,x=i)
  plt.show()

df=pd.get_dummies(data=df,columns=cat_cols,drop_first=True,dtype='int')

df.shape

plt.figure(figsize=(25,15))
sns.heatmap(df.corr(),annot=True)
plt.show()

X=df.drop('booking status_Not_Canceled',axis=1)
y=df['booking status_Not_Canceled']

# splitting data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20,shuffle=True)

X_train.shape,y_train.shape,X_test.shape,y_train.shape

# model building
model=LogisticRegression(max_iter=5000)
model.fit(X_train,y_train)
pred=model.predict(X_test)

cf=confusion_matrix(y_test,pred)

ConfusionMatrixDisplay(cf).plot()
plt.show()

print(f"accuracy score:{accuracy_score(y_test,pred)}")
print(f"precision score:{precision_score(y_test,pred)}")

