# -*- coding: utf-8 -*-
"""lvadsusr180_riddhi bhowmick .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_mYXeKPZ7cMWCb31DaaUmmwEHzI83X3
"""

# question1
width=float(input("enter width: "))
length=float(input("enter length: "))
area=width*length
print("area: ",area)
if area<300:
  print("small")
elif area<600:
  print("medium")
else:
  print("large")
unit_price=float(input("enter unit price: "))
print("total_price: ",unit_price*area)

# question 2

def suggest_health(bmi):
  health_advice={1:'taking good care of health',2:'need to workout',3:'burn more eat less'}
  diet_plan={1:'eat more',2:'eat less',3:'eat healthy'}
  if bmi<100:
    print("diet_plan: ",diet_plan[0])
    print("health_advice: ",health_advice[0])

  elif bmi<200:
    print("diet_plan: ",diet_plan[1])
    print("health_advice: ",health_advice[1])
  else:
    print("diet_plan: ",diet_plan[2])
    print("health_advice: ",health_advice[2])


def add_data(my_dict_bmi,my_dict_weight,my_dict_height):
  name=input("enter name: ")
  weight=float(input("enter weight: "))
  height=float(input("enter height: "))
  bmi=weight*height
  my_dict_bmi[name]=bmi
  my_dict_weight[name]=weight
  my_dict_height[name]=height
  print("name",name)
  print("weight",my_dict_weight[name])
  print("weight",my_dict_height[name])

  suggest_health(bmi)
  return my_dict_bmi,my_dict_weight,my_dict_height

# age=float(input("enter age: "))
my_dict_bmi={}
my_dict_weight={}
my_dict_height={}
my_dict_bmi,my_dict_weight,my_dict_height=add_data(my_dict_bmi,my_dict_weight,my_dict_height)

# question 3
def grades():
  maths=input("enter grades in maths: ")
  english=input("enter grades in english: ")
  computer=input("enter grades in computer: ")
  grades={'maths':maths,'english':english,'computer':computer}
  return grades

students={}
result={}
while True:
  name=input("enter name: ")
  result[name]=grades()
  x=int(input("if want to update marks press 1,if want to delete records press 2: " ))
  if x==1:
    name1=input("enter name of student: ")
    if name1 in result.keys():
      subject=input("enter subject name for updating marks: ")
      result[name][subject]=input("enter grades: ")

    else:
      print("no such student")
  if x==2:
    name2=input("enter name: ")
    if name2 not in result.keys():
               print("no such student")
    else:
      result.remove(name2)

  x=int(input("want to enter more details of student:if yes press 1 else 0 "))
  if x!=1:
    break


print(result)

# question4
age=int(input("enetr age: "))
movies={'children':['a','b','c'],'teen':['x','y','z'],'adult':['u''o','p']}


if age<12:
  x='children'
  print("Children")
  print("movies to watch",movies[x])
elif age<18:
  x="teen"
  print("teen")
  print("movies to watch",movies[x])
elif age<18:
  x="adult"
  print("adult")
  print("movies to watch",movies[x])

# question 5
database=[]
targted_cust=[]
n=int(input("total ids: "))
for i in range(n):
  # creating ids
  database.append(i)
for i in database:
  if i%2==0:
    targted_cust.append(i)
print("targeted customer ids",targted_cust)

#question6

database_password={"riddhi":'123a',"raj":'234x'}

while True:
  name=input("enter name: ")
  if name in database_password.keys():
    pass_=input("enter password: ")
    if(database_password[name]==pass_):
      print("entry accepted")
    else:
      print("entry denined")
  else:
    print("not found in db")
  break

#question7

customer_rating=[]
for i in range(3):
  customer_rating.append(int(input("enter rating: ")))
total_avg=sum(customer_rating)/len(customer_rating)
if total_avg<10:
  print("need to improve")
 else:
  print("customer happy")

#question 8
def count_vowels(text):
  x=[i for i in text if i in 'aeiou']
  return(len(x))
text=input("enter text: ")
print("counted vowels:",count_vowels(text))

# question9
import datetime
reminder=True
if reminder is True:
  print(datetime.date())
  print("reminder")

#question10
loan_repayment=float(input("input laon: "))
print(loan repayment)

#question11
valid_vote=["a","b","c"]
n=int(input("enter number of valid voters: "))
valid_count=0
non_valid_count=0
for i in range(n):
  x=input("enter vote: ")
  if x in valid_vote:
    valid_count+=1
  else:
    non_valid_count+=1
print("valid_count:",valid_count)
print("non_valid_count",non_valid_count)

# question 12
def sum(*data):
  sum=0
  for i in data:
    sum+=i
  return sum
def multiply(data1,data2):
  return data1*data2
def subtract(data1,data2):
   return data1-data2

def divide(data1,data3):
   return data1/data3

a=float(input("enter number: "))
b=float(input("enter number: "))

print(sum(a,b))
print(subtract(a,b))
print(multiply(a,b))
print(divide(a,b))



# question 13
text=input("enter text: ")
with open("file.txt",'wb') as file:
  file.write(text)

# question14:
with open("file.txt",'rb') as data:
  print(data)

#question 15
text=input("enter text: ")
with open("file.txt",'wb') as file:
  file.write(text)